### ISSUE TITLE
커뮤니티 페이지 생성

### ISSUE THREAD

**Issue by monsterKyu** [LESSERAFIM-Aespa/TripMate#17]
## **Feature Description**
[커뮤니티]
게시글 리스트(main) - mosterKyu
게시글 상세화면(detail) - young
게시글 작성화면(write) - youneeo,mosterKyu

- 커뮤니티 Write프래그먼트 Detail프래그먼트 생성

## **Todo list**
- [ ] Write 프래그먼트 생성
- [ ] Detail 프래그먼트 생성

**Comment by seojh5939** [comment]
기능구현에 대한부분이 좀 더 디테일하게 적혀있어야 할 것 같습니다 ㅎㅎ
파이어베이스를 연동한 이후 어떤식으로 어떤 페이지를 구현할지에대한 구체적인 정보가 필요합니다
