### ISSUE TITLE
[help]좋아요 기능 문제

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#88]
- 파이어베이스의 데이터베이스에 아래와같은 형식으로 저장되고 있습니다.

![image](https://raw.githubusercontent.com/seongssu/ImageUrl/main/hotfix1.png) 

- 아래와 같이 for문을 2중으로 돌려서 데이터를 받아온 후 라이브데이터로 데이터를 관리하고 있고,  

                for (userPostSnapshot in snapshot.children) {
                    for (postSnapshot in userPostSnapshot.children) {
                        val postId = postSnapshot.key
                        val postModel = postSnapshot.getValue(CommunityModel::class.java)
                        if (postId != null && postModel != null) {
                            allCommunityData.add(postModel)
                        }
                    }
                }
                if(!allCommunityData.isNullOrEmpty()){
                    _dataModelList.value = allCommunityData
                }
                _isLoading.value = false           
            }

-  데이터 수정과정을 거친 후 아래와 같이 다시 리스트로 만든 후 각각의 리스트의 키값이 정해져있으므로 해당 키값에 수정된 정보를 저장하려고 하고 있었습니다.

        val updateList = arrayListOf<CommunityModel>()
        list?.let {
            updateList.addAll(it)
        }
        for (modelItem in updateList){
            val modelId = modelItem.id
            val commuRef = commuDatabase.getReference("CommunityData").child(modelId)
            commuRef.setValue(updateList)
        }

**문제점**
- 맨 아랫줄 commuRef.setValue에 updateList를 넣어준 이유는 데이터베이스에 저장할때 리스트형태로 저장하기 위해서입니다.
- for문을 돌린 이유는 각각의 아이템마다 누가 작성한건지 알 수 있는 uid키값이 들어있는데 그 키값을 뽑아서 해당 아이템들을 그 키값 밑으로 넣기 위해 돌렸습니다. 그래서 updateList로 저장을 시켰습니다.
- **그런데 작성하고보니 for문에 있으면 안될것같네요 ㅠㅠ**
- 위 에서 수정된 정보는 좋아요 버튼을 눌렀을때 좋아요갯수가 1증가하거나 해제하면 1감소한 수정된 데이터를 파이어베이스에 저장하려는 상황입니다.
- 우선 데이터 키값이 내 uid값이면 좋아요를 눌렀을때 정보도 수정이 잘 되고 문제가없었습니다.
- 하지만 다른사람 데이터가 데이터베이스에 추가되는 순간부터 다른사람 정보가 내 uid키값 밑에 중복으로 추가 저장되는 상황이 있었습니다.

## **To Reproduce**

- 데이터 수정 결과는 문제가없는데 수정된 데이터가 저장되는 경로가 문제가 있는것 같습니다.
- 애초에 저장되는 데이터 클래스를 맵형태로 변환해보고, 경로지정을 변경도 해보고 여러가지 데이터 클래스 형식으로 만들어봤습니다.
- 경로지정도 수정해보고, uid도 하드코딩해서 직접 해당 경로에 지정해보고 여러 방식을 택해봤습니다.
- 데이터 저장하는곳을 라이브데이터가 아닌 해당 Fragment로 변경해서 작업해봤지만 해결되지 않았습니다.
- 답이 간단하게 나올때도 있는데, 여러가지를 해보다보니 머리가 복잡해서 도움을 요청합니다!

## **Expected behavior**

- 제가 원하는 방향은 각각의 유저가 작성한 글이 데이터베이스에 저장되고, 해당 글에 대해 좋아요를 눌렀을때 누적으로 저장되어 좋아요가 많은 게시판 글들을 강조해서 볼 수 있게 만들고 싶습니다.

**Comment by youneeo** [comment]
커뮤니티데이터 바로 하위노드가 리스트형태로 키값형태가 아닌상태로 저장되게 하는 방법은 어떨까요?
